use crate::config::{Config, group_title};

pub const HOOKS: &[&str] = &["commit-msg", "pre-push"];

pub fn hook_shim(name: &str) -> String {
    format!(
        r#"#!/bin/sh
# Installed by `gir init`. Commit this file; see `gir explain hooks`.
if command -v gir >/dev/null 2>&1; then
	exec gir hook {name} "$@"
fi
mode=$(git config --file "$(git rev-parse --show-toplevel)/.girconfig" gir.hookMissing 2>/dev/null)
if [ "$mode" = "fail" ]; then
	echo "gir: not installed, {name} check blocked (gir.hookMissing=fail)" >&2
	exit 1
fi
echo "gir: not installed, {name} check skipped" >&2
exit 0
"#
    )
}

pub const GIT_IT_RIGHT_MD: &str = r#"# git-it-right

This repository uses [gir (git-it-right)](https://github.com/flatrick/git-it-right) to keep commit messages consistent.
gir checks every commit message against [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/), fixes safe mistakes for you, and explains anything it rejects.
Consistent messages make the history readable and let tools build the changelog and the next version number from it.

## Contributing: once per clone

1. Install gir: see [Install](https://github.com/flatrick/git-it-right#install).
2. In your clone, run `gir init`.

Git never turns on hooks from a fresh clone, so step 2 is needed in every clone.
It sets `core.hooksPath` to `.githooks` and restores the hooks and `.girconfig` if they are missing.

## Writing commits

Write messages as `<type>[(scope)][!]: <description>`, for example `fix(api): return 404 for unknown users`.

- `gir explain types` lists the types this repository allows (they are set in `.girconfig`).
- When a commit is rejected, the message names a rule in brackets, such as `[type-unknown]`; `gir explain <rule>` explains it.
- `gir fixup` and `gir explain fixup` cover fixing an earlier commit on your branch.

## Maintainers: checking contributions

Without CI, check a contributor's branch before you merge it:

```sh
gir lint --range main..<their-branch>
```

With CI, run the same check on every pull request:

```sh
gir lint --range origin/main..HEAD
```

This also catches commits made with `git commit --no-verify`.

## Changelog (optional)

`gir init` also writes `cliff.toml`, a configuration for [git-cliff](https://git-cliff.org) that matches this repository's commit types.
Contributors do not need it; it is for whoever cuts a release:

```sh
git-cliff -o CHANGELOG.md     # write the changelog
git-cliff --bumped-version    # print the next version
```

gir works without it.
If you do not want it, delete `cliff.toml` and commit the deletion; `gir init` will not add it back.

## This file

`gir init` wrote this file.
Edit it, or delete it and commit the deletion; `gir init` will not add it back.
`gir init --optional` restores a deleted `cliff.toml` or `GIT-IT-RIGHT.md` without touching files you changed.
"#;

pub const GITATTRIBUTES: &str = "\
# Normalise line endings in the repo; check out with LF except where Windows tools need CRLF.
* text=auto eol=lf
*.cmd text eol=crlf
*.bat text eol=crlf
*.sln text eol=crlf

*.png binary
*.jpg binary
*.jpeg binary
*.gif binary
*.ico binary
*.webp binary
*.pdf binary
*.zip binary
*.gz binary
*.7z binary
*.woff binary
*.woff2 binary
*.ttf binary
*.exe binary
*.dll binary
*.so binary
*.dylib binary
";

pub const EDITORCONFIG: &str = "\
root = true

[*]
charset = utf-8
end_of_line = lf
insert_final_newline = true
trim_trailing_whitespace = true
indent_style = space
indent_size = 4

[*.{md,markdown}]
trim_trailing_whitespace = false

[*.{yml,yaml,json,toml}]
indent_size = 2

[{*.cmd,*.bat,*.sln}]
end_of_line = crlf

[Makefile]
indent_style = tab
";

/// (marker file or extension that reveals the stack, ignore pattern, path that pattern must ignore)
pub const IGNORE_RULES: &[(&str, &str, &str)] = &[
    ("Cargo.toml", "/target/", "target/gir-probe"),
    ("package.json", "node_modules/", "node_modules/gir-probe"),
    (".csproj", "bin/", "bin/gir-probe"),
    (".csproj", "obj/", "obj/gir-probe"),
    (".sln", "bin/", "bin/gir-probe"),
    (".sln", "obj/", "obj/gir-probe"),
    ("pyproject.toml", "__pycache__/", "__pycache__/gir-probe"),
    ("pyproject.toml", ".venv/", ".venv/gir-probe"),
    ("requirements.txt", "__pycache__/", "__pycache__/gir-probe"),
    ("requirements.txt", ".venv/", ".venv/gir-probe"),
    ("go.mod", "/vendor/", "vendor/gir-probe"),
    ("*", ".DS_Store", ".DS_Store"),
    ("*", "Thumbs.db", "Thumbs.db"),
    ("*", ".env", ".env"),
];

pub fn cliff_toml(cfg: &Config) -> String {
    let parsers: Vec<String> =
        cfg.types.iter().map(|t| format!("  {{ message = \"^{t}(\\\\(|!|:)\", group = \"{}\" }},", group_title(t))).collect();
    format!(
        r##"# git-cliff config generated by `gir init` from gir.types in .girconfig.
# Changelog: git-cliff -o CHANGELOG.md    Next version: git-cliff --bumped-version
[changelog]
header = "# Changelog\n"
body = """
{{% if version %}}## {{{{ version }}}} - {{{{ timestamp | date(format="%Y-%m-%d") }}}}{{% else %}}## Unreleased{{% endif %}}
{{% for group, commits in commits | group_by(attribute="group") %}}
### {{{{ group }}}}
{{% for commit in commits %}}
- {{% if commit.scope %}}**{{{{ commit.scope }}}}:** {{% endif %}}{{% if commit.breaking %}}[**breaking**] {{% endif %}}{{{{ commit.message | upper_first }}}}
{{%- endfor %}}
{{% endfor %}}
"""
trim = true

[git]
conventional_commits = true
filter_unconventional = true
protect_breaking_commits = true
sort_commits = "oldest"
commit_parsers = [
  {{ message = "^(fixup|squash|amend)!", skip = true }},
{}
]
"##,
        parsers.join("\n")
    )
}
