import os, sys
sys.path.insert(0, os.path.dirname(__file__))
from edge import repo, commit, sh, gir, log, case, ENV, GIR
import subprocess

case("14 CRLF file split")
d = repo()
open(f"{d}/.gitattributes", "w").write("* -text\n"); sh(d, "git", "add", "-A"); sh(d, "git", "commit", "-qm", "chore: attrs")
commit(d, "a", "a1\r\na2\r\n", "feat: a")
commit(d, "b", "b1\r\nb2\r\n", "feat: b")
open(f"{d}/a", "w", newline="").write("A1\r\na2\r\n"); open(f"{d}/b", "w", newline="").write("b1\r\nB2\r\n")
sh(d, "git", "add", "-A")
print(gir(d, "fixup", "--split"))
print(log(d))

case("15 sparse checkout + split")
d = repo()
commit(d, "in/a", "a\n", "feat: a")
commit(d, "in/b", "b\n", "feat: b")
commit(d, "out/c", "c\n", "feat: c")
sh(d, "git", "sparse-checkout", "set", "in")
open(f"{d}/in/a", "w").write("A\n"); open(f"{d}/in/b", "w").write("B\n")
sh(d, "git", "add", "-A")
print("before:", repr(sh(d, "git", "status", "--short").stdout))
print(gir(d, "fixup", "--split"))
print(log(d))
print("after:", repr(sh(d, "git", "status", "--short").stdout))

case("16 assume-unchanged / skip-worktree bit after split")
d = repo()
commit(d, "a", "a\n", "feat: a")
commit(d, "b", "b\n", "feat: b")
commit(d, "cfg", "c\n", "feat: cfg")
sh(d, "git", "update-index", "--skip-worktree", "cfg")
open(f"{d}/cfg", "w").write("local edit\n")
open(f"{d}/a", "w").write("A\n"); open(f"{d}/b", "w").write("B\n")
sh(d, "git", "add", "a", "b")
print("before:", repr(sh(d, "git", "status", "--short").stdout))
print(gir(d, "fixup", "--split"))
print("after:", repr(sh(d, "git", "status", "--short").stdout))

case("17 interactive picker with several targets where a hunk spans -> choose s")
d = repo()
commit(d, "f", "one\n", "feat: one")
commit(d, "f", "one\ntwo\n", "feat: two")
open(f"{d}/f", "w").write("one\nmid\ntwo\n")
sh(d, "git", "add", "-A")
r = subprocess.run([GIR, "fixup"], cwd=d, input="s\n", capture_output=True, text=True, env=dict(ENV, GIR_INTERACTIVE="1"))
print(r.returncode, r.stderr)

case("18 --split with a new file, interactive picker")
d = repo()
commit(d, "a", "a\n", "feat: a")
commit(d, "b", "b\n", "feat: b")
open(f"{d}/new", "w").write("n\n"); open(f"{d}/a", "w").write("A\n"); open(f"{d}/b", "w").write("B\n")
sh(d, "git", "add", "-A")
r = subprocess.run([GIR, "fixup", "--split"], cwd=d, input="1\n", capture_output=True, text=True, env=dict(ENV, GIR_INTERACTIVE="1"))
print(r.returncode, r.stderr)
print(log(d), sh(d, "git", "show", "--stat", "--format=", "HEAD").stdout)

case("19 hunk blamed to a merge-side commit; pick list from base..HEAD includes merged branch commits")
d = repo()
commit(d, "a", "a\n", "feat: a")
sh(d, "git", "switch", "-qc", "side"); commit(d, "s", "s\n", "feat: side"); sh(d, "git", "switch", "-q", "topic")
sh(d, "git", "merge", "-q", "--no-ff", "-m", "Merge side", "side")
open(f"{d}/new", "w").write("n\n"); sh(d, "git", "add", "-A")
r = subprocess.run([GIR, "fixup"], cwd=d, input="q\n", capture_output=True, text=True, env=dict(ENV, GIR_INTERACTIVE="1"))
print(r.returncode, r.stderr)
